openapi: 3.0.3
info:
  title: Drinks & Snacks API
  version: 1.0.0
  description: API for managing stores and their drinks and snacks

servers:
  - url: http://localhost:8080

tags:
  - name: Auth
    description: Operations related to authentication
  - name: Users
    description: Operations related to users
  - name: Stores
    description: Operations related to stores
  - name: Drinks
    description: Operations related to drinks

security:
  - bearerAuth: []

paths:

  /:
    get:
      summary: Health check
      responses:
        '200':
          description: API is alive
          content:
            text/plain:
              schema:
                type: string
                example: "I'm alive!"


  /api/v1/auth/register:
    post:
      tags:
        - Auth
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered
        '400':
          description: Username already taken

  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Logged in
        '400':
          description: Wrong username or password

  /api/v1/users/me:
    get:
      tags:
        - Users
      summary: Get own user data
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'

    delete:
      tags:
        - Users
      summary: Delete own user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteAccountRequest'
      responses:
        '204':
          description: Account deleted
        '400':
          description: Wrong password

  /api/v1/users:
    get:
      tags:
        - Users
      summary: Get all users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'

  /api/v1/users/{id}:
    get:
      tags:
        - Users
      summary: Get a user by ID
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
    delete:
      tags:
        - Users
      summary: Delete user
      responses:
        '204':
          description: User deleted

  /api/v1/stores:
    get:
      tags:
        - Stores
      summary: Get all stores
      responses:
        '200':
          description: List of stores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StoreDTO'

    post:
      tags:
        - Stores
      summary: Create a new store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStoreRequest'
      responses:
        '201':
          description: Store created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoreDTO'
        '400':
          description: Bad request

  /api/v1/stores/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      tags:
        - Stores
      summary: Get store by ID
      responses:
        '200':
          description: Store found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoreDTO'
        '404':
          description: Store not found
        '400':
          description: Missing or malformed id

    delete:
      tags:
        - Stores
      summary: Delete store
      responses:
        '204':
          description: Store deleted
        '400':
          description: Missing or malformed id

  /api/v1/stores/{storeId}/drinks:
    parameters:
      - name: storeId
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      tags:
        - Drinks
      summary: Get all drinks for a store
      parameters:
        - name: alcoholic
          in: query
          required: false
          schema:
            type: boolean
        - name: packaging
          in: query
          required: false
          schema:
            type: string
            enum: [CAN, BOTTLE]
      responses:
        '200':
          description: List of drinks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DrinkDTO'
        '400':
          description: Missing or malformed storeId

    post:
      tags:
        - Drinks
      summary: Create drink in store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDrinkRequest'
      responses:
        '201':
          description: Drink created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DrinkDTO'
        '400':
          description: Bad request

  /api/v1/stores/{storeId}/drinks/{id}:
    parameters:
      - name: storeId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      tags:
        - Drinks
      summary: Get drink by ID
      responses:
        '200':
          description: Drink found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DrinkDTO'
        '404':
          description: Drink not found
        '400':
          description: Missing or malformed id

    delete:
      tags:
        - Drinks
      summary: Delete drink
      responses:
        '204':
          description: Drink deleted
        '400':
          description: Missing or malformed id

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    StoreDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        ownerUsername:
          type: string
      required:
        - id
        - name
        - ownerUsername

    CreateStoreRequest:
      type: object
      properties:
        name:
          type: string
      required:
        - name

    DrinkDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        milliliters:
          type: integer
        alcoholPercentage:
          type: number
          minimum: 0.0
        alcoholic:
          type: boolean
        packaging:
          type: string
          enum: [CAN, BOTTLE]
      required:
        - id
        - name
        - milliliters
        - alcoholPercentage
        - alcoholic
        - packaging

    CreateDrinkRequest:
      type: object
      properties:
        name:
          type: string
        milliliters:
          type: integer
        alcoholPercentage:
          type: number
          minimum: 0.0
        packaging:
          type: string
          enum: [CAN, BOTTLE]

      required:
        - name
        - milliliters
        - alcoholPercentage
        - packaging

    SessionDTO:
      type: object
      properties:
        accessToken:
          type: string
      required:
        - accessToken

    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
      required:
        - username
        - password
        - firstName
        - lastName

    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    UserDTO:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
      required:
        - username
        - firstName
        - lastName

    DeleteAccountRequest:
      type: object
      properties:
        password:
          type: string