ktor:
    application:
        modules:
            - de.okan.drink_and_snack_api.ApplicationKt.module
    deployment:
        port: 8080

db:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
    driver: org.h2.Driver
    username: ""
    password: ""

auth:
    jwt:
        secret: "your-256-bit-secret"
        issuer: "your-app"
        audience: "your-app-users"
        realm: "Access to the '/api' path"
        duration_in_ms: 60000