ktor:
    application:
        modules:
            - de.okan.drinks_and_snacks_api.ApplicationKt.module
    deployment:
        port: ${PORT}

db:
    url: ${DB_URL}
    driver: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

auth:
    jwt:
        secret: ${JWT_SECRET}
        issuer: "drinks-and-snacks-api"
        audience: "drinks-and-snacks-api-users"
        realm: "Access to the '/api' path"
        duration_in_ms: 60000